/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_addbean_autils_ndk_NativeJni */

#ifndef _Included_com_addbean_autils_ndk_NativeJni
#define _Included_com_addbean_autils_ndk_NativeJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_addbean_autils_ndk_NativeJni
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_addbean_autils_ndk_NativeJni_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_addbean_autils_ndk_NativeJni
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_addbean_autils_ndk_NativeJni_getString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_addbean_autils_ndk_NativeJni
 * Method:    blur
 * Signature: ([IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_addbean_autils_ndk_NativeJni_blur
  (JNIEnv *, jobject, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
